title: Max's Puzzle Page
author: Max Mayer
email: max@maxcyrusmayer.com
description: My solutions to the Jane Street monthly puzzles.

remote_theme: andrewhwanpark/dark-poole

plugins:
  - jekyll-remote-theme
