title: My Cool Dark Blog
author: Max Mayer
email: you@example.com
description: A personal blog

# Optional social links
github_username: maxmayer
linkedin_username: your-linkedin

remote_theme: andrewhwanpark/dark-poole

# Make sure GitHub Pages can build it:
plugins:
  - jekyll-remote-theme
